POST http://localhost:8080/add/READ
Content-Type: application/json

{
  "username": "ivan",
  "password": "1234"
}


###
GET http://localhost:8080/authorize?user=ivan&password=1234
Accept: application/json

###

###
GET http://localhost:8080/authorize?user=&password=1234
Accept: application/json

###